App\Entity\Location:
    properties:
        city:
            - NotBlank: { groups: ['create', 'edit'] }
        country:
            - NotBlank: { groups: ['create', 'edit'] }
        latitude:
            - NotBlank: { groups: ['create', 'edit'] }
            - Type:
                  type: numeric
                  groups: ['create', 'edit']
            - Range:
                  min: -90
                  max: 90
                  notInRangeMessage: 'Szerokość geograficzna musi być między -90 a 90.'
                  groups: ['create', 'edit']
        longitude:
            - NotBlank: { groups: ['create', 'edit'] }
            - Type:
                  type: numeric
                  groups: ['create', 'edit']
            - Range:
                  min: -180
                  max: 180
                  notInRangeMessage: 'Długość geograficzna musi być między -180 a 180.'
                  groups: ['create', 'edit']


App\Entity\Measurement:
    properties:
        date:
            - NotBlank: { groups: ['create', 'edit'] }
        location:
            - NotNull: { groups: ['create', 'edit'] }

App\Entity\Attributes:
    properties:
        name:
            - NotBlank: { groups: ['create', 'edit'] }
        unit:
            - NotBlank: { groups: ['create', 'edit'] }

App\Entity\Value:
    properties:
        value:
            - NotBlank: { groups: ['create', 'edit'] }
            - Type:
                  type: numeric
                  groups: ['create', 'edit']
        measurement:
            - NotNull: { groups: ['create', 'edit'] }
        attribute:
            - NotNull: { groups: ['create', 'edit'] }

